service:
  name: url-shortener

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true # Run migrations upon local DynamoDB start

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

functions:
  getUrl:
    handler: handler.getUrl
    events:
      - http:
          method: get
          path: /{id}
          request:
          parameters:
             paths:
               id: true
  createUrl:
    handler: handler.createUrl
    events:
      - http:
          method: post
          path: /register.json
          parameters:
            querystrings:
              url: true
  getStats:
    handler: handler.getStats
    events:
      - http:
          method: get
          path: /{id}/stats
          request:
          parameters:
             paths:
               id: true

resources:
  Resources:
    urlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: urls
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: UrlIndex
            KeySchema:
              - AttributeName: url
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - id
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
