service:
  name: vingle-app

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true # Run migrations upon local DynamoDB start

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  getUrl:
    handler: handler.getUrl
    events:
      - http:
          method: get
          path: urls/{id}
          request:
          parameters:
             paths:
               id: true
  createUrl:
    handler: handler.createUrl
    events:
      - http:
          method: post
          path: urls
          parameters:
            querystrings:
              url: true
  getStats:
    handler: handler.getStats
    events:
      - http:
          method: get
          path: urls/{id}/stats
          request:
          parameters:
             paths:
               id: true

resources:
  Resources:
    urlsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: urls
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          # - AttributeName: url
          #   AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
